# Generated by Django 4.1.7 on 2023-04-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('mrot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('birth_date', models.DateField()),
                ('department', models.CharField(max_length=20, verbose_name='Подразделение')),
                ('position', models.CharField(max_length=20, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата нарушения')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('fine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Штраф')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала отпуска')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания отпуска')),
                ('vacation_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество отпускных дней')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Отработано часов')),
                ('piecework_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за сдельную работу')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Учет рабочего времени',
                'verbose_name_plural': 'Учет рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала больничного')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания больничного')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='Количество дней')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медицинская справка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Больничный лист',
                'verbose_name_plural': 'Больничные листы',
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированный оклад'), ('hourly', 'Почасовая оплата'), ('piecework', 'Сдельная оплата')], max_length=10, verbose_name='Тип заработной платы')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('worked_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacation_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sick_leave_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, verbose_name='Номер договора')),
                ('contract_type', models.CharField(max_length=255, verbose_name='Тип договора')),
                ('date', models.DateField(verbose_name='Дата заключения соглашения')),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированный оклад'), ('hourly', 'Почасовая оплата'), ('piecework', 'Сдельная оплата')], max_length=10, verbose_name='Тип заработной платы')),
                ('salary_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер оклада или ставки')),
                ('bonus_conditions', models.CharField(max_length=255, verbose_name='Условия начисления дополнительных выплат')),
                ('work_schedule', models.CharField(max_length=255, verbose_name='Режим работы и график работы')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('hiring_conditions', models.CharField(max_length=255, verbose_name='Условия приема на работу и увольнения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Договор о найме',
                'verbose_name_plural': 'Договоры о найме',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начисления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заключения соглашения')),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированный оклад'), ('hourly', 'Почасовая оплата'), ('piecework', 'Сдельная оплата')], max_length=10, verbose_name='Тип заработной платы')),
                ('salary_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка заработной платы')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='График работы')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollcalculation.employmentcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
    ]
